# This is a basic workflow to help you get started with Actions

name: 部署space-srm

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'docker image tag'
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: 部署
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: helm部署
        run: |
          echo "image tag: ${{ inputs.tag }}"
          helm repo update
          helm upgrade --install space-srm kjhch/space-srm --set image.tag=${{ inputs.tag }}
